<?php

/**
 * Implements hook_cfrplugin_info().
 */
function atomiumprofiler_cfrplugin_info() {
  if (NULL === drupal_get_filename('theme', 'atomium')) {
    drupal_set_message('atomiumprofiler is enabled, but atomium is nowhere to be found.', 'warning');
    return [];
  }
  return cfrplugindiscovery()->moduleFileScanPsr4(__FILE__);
}

/**
 * Implements hook_theme().
 */
function atomiumprofiler_theme() {
  return [
    /* @see theme_atomiumprofiler_example_with_element() */
    'atomiumprofiler_example_with_element' => [
      'render element' => 'element',
    ],
    /* @see theme_atomiumprofiler_example_with_variables() */
    'atomiumprofiler_example_with_variables' => [
      'variables' => array('text' => NULL),
    ],
    /* @see theme_atomiumprofiler_example_minimal() */
    'atomiumprofiler_example_minimal' => [
      'variables' => array('text' => NULL),
    ],
  ];
}

/**
 * @param array $variables
 *
 * @return string
 */
function theme_atomiumprofiler_example_with_element(array $variables) {
  return __FUNCTION__;
}

/**
 * @param array $variables
 *
 * @return string
 */
function theme_atomiumprofiler_example_with_variables(array $variables) {
  return check_plain($variables['text']);
}

/**
 * @param array $variables
 *
 * @return string
 */
function theme_atomiumprofiler_example_minimal(array $variables) {
  return __FUNCTION__;
}

/**
 * Implements hook_system_theme_engine_info().
 */
function atomiumprofiler_system_theme_engine_info() {
  $theme_engines['atomiumengine'] = drupal_get_path('module', 'atomiumprofiler') . '/atomiumengine.engine';
  return $theme_engines;
}
